Repository noranbear/how-about-e-medicine, pull requests merged in 2022-07, with the labels that each got.

#1 :memo:Create Pull Request Template
  .github/pull_request_template
Labels: documentation

#4 ✨ Add default files like Util.java and logback.xml
  bin/.github/ISSUE_TEMPLATE/bug_report.md
  bin/.github/ISSUE_TEMPLATE/custom.md
  bin/.github/ISSUE_TEMPLATE/feature-request.md
  bin/.github/ISSUE_TEMPLATE/page-request.md
  bin/.github/pull_request_template
  bin/.gitignore
  bin/.mvn/wrapper/maven-wrapper.jar
  bin/.mvn/wrapper/maven-wrapper.properties
  bin/README.md
  bin/mvnw
  bin/mvnw.cmd
  bin/pom.xml
  bin/src/main/java/com/multi/Medicine2Application.class
  bin/src/main/java/com/multi/ServletInitializer.class
  bin/src/main/resources/application.properties
  bin/src/test/java/com/multi/Medicine2ApplicationTests.class
  src/main/java/com/multi/frame/Util.java
  src/main/resources/logback.xml
Labels: enhancement

#7 🗃️ 📝 MySQL 드라이버의 DB명 변경 및 README.md 첫 번째 내용 쓰기
  bin/README.md
  src/main/resources/application.properties
Labels: documentation, enhancement

#8 ✨✅ CRUD Mymedi 구축
  src/main/java/com/multi/biz/MymediBiz.java
  src/main/java/com/multi/frame/Biz.java
  src/main/java/com/multi/mapper/MymediMapper.java
  src/main/java/com/multi/mybatis/mymedi.xml
  src/main/java/com/multi/vo/MymediVo.java
  src/test/java/com/multi/MymediDeleteTests.java
  src/test/java/com/multi/MymediInsertTests.java
  src/test/java/com/multi/MymediSelectAllTests.java
  src/test/java/com/multi/MymediSelectTests.java
  src/test/java/com/multi/MymediUpdateTests.java
Labels: enhancement

#16 📝Remove duplicate
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#27 ✨ ✅ 모든 CRUD users, plist, alarm, mymedi, pmedi 구축 및 테스트 완료
  src/main/java/com/multi/biz/AlarmBiz.java
  src/main/java/com/multi/biz/PlistBiz.java
  src/main/java/com/multi/biz/PmediBiz.java
  src/main/java/com/multi/biz/UsersBiz.java
  src/main/java/com/multi/mapper/AlarmMapper.java
  src/main/java/com/multi/mapper/PlistMapper.java
  src/main/java/com/multi/mapper/PmediMapper.java
  src/main/java/com/multi/mapper/UsersMapper.java
  src/main/java/com/multi/mybatis/alarmmapper.xml
  src/main/java/com/multi/mybatis/mymedimapper.xml
  src/main/java/com/multi/mybatis/plistmapper.xml
  src/main/java/com/multi/mybatis/pmedimapper.xml
  src/main/java/com/multi/mybatis/usersmapper.xml
  src/main/java/com/multi/vo/AlarmVo.java
  src/main/java/com/multi/vo/MymediVo.java
  src/main/java/com/multi/vo/PlistVo.java
  src/main/java/com/multi/vo/PmediVo.java
  src/main/java/com/multi/vo/UsersVo.java
  src/test/java/com/multi/MymediDeleteTests.java
  src/test/java/com/multi/MymediInsertTests.java
  src/test/java/com/multi/MymediSelectAllTests.java
  src/test/java/com/multi/MymediSelectTests.java
  src/test/java/com/multi/MymediUpdateTests.java
  src/test/java/com/multi/alarm/AlarmDeleteTests.java
  src/test/java/com/multi/alarm/AlarmInsertTests.java
  src/test/java/com/multi/alarm/AlarmSelectAllTests.java
  src/test/java/com/multi/alarm/AlarmSelectTests.java
  src/test/java/com/multi/alarm/AlarmUpdateTests.java
  src/test/java/com/multi/mymedi/MymediDeleteTests.java
  src/test/java/com/multi/mymedi/MymediInsertTests.java
  src/test/java/com/multi/mymedi/MymediSelectAllTests.java
  src/test/java/com/multi/mymedi/MymediSelectTests.java
  src/test/java/com/multi/mymedi/MymediUpdateTests.java
  src/test/java/com/multi/plist/PlistDeleteTests.java
  src/test/java/com/multi/plist/PlistInsertTests.java
  src/test/java/com/multi/plist/PlistSelectAllTests.java
  src/test/java/com/multi/plist/PlistSelectTests.java
  src/test/java/com/multi/plist/PlistUpdateTests.java
  src/test/java/com/multi/pmedi/PmediDeleteTests.java
  src/test/java/com/multi/pmedi/PmediInsertTests.java
  src/test/java/com/multi/pmedi/PmediSelectAllTests.java
  src/test/java/com/multi/pmedi/PmediSelectTests.java
  src/test/java/com/multi/pmedi/PmediUpdateTests.java
  src/test/java/com/multi/users/UsersDeleteTests.java
  src/test/java/com/multi/users/UsersInsertTests.java
  src/test/java/com/multi/users/UsersSelectAllTests.java
  src/test/java/com/multi/users/UsersSelectTests.java
  src/test/java/com/multi/users/UsersUpdateTests.java
Labels: enhancement

#35 ✨✅ OCR API-envelope 및 box 연동 및 작동 테스트 완료
  pom.xml
  src/main/java/com/multi/controller/AJAXController.java
  src/main/java/com/multi/restapi/OCRBoxAPI.java
  src/main/java/com/multi/restapi/OCREnvelopeAPI.java
  src/main/resources/static/img/box/test_box.jpg
  src/main/resources/static/img/envelope/test_envelope3.jpg
  src/test/java/com/multi/api/OCRBoxTest.java
  src/test/java/com/multi/api/OCREnvelopeTest.java
Labels: enhancement

#38 💄 메인 페이지 사이드 바에 유저로고 추가
  src/main/resources/templates/index.html
Labels: enhancement

#54 💄 메인페이지 기본 화면 구현
  src/main/resources/static/assets/ezocss/indexpage.css
  src/main/resources/static/img/fake_logo.png
  src/main/resources/templates/index.html
Labels: enhancement

#58 💄 add signup page
  src/main/resources/templates/signup.html
Labels: enhancement

#62 ⚡️ signin 기능 구현
  src/main/java/com/multi/controller/MainController.java
  src/main/resources/templates/index.html
  src/main/resources/templates/signin.html
Labels: enhancement

#59 💄 약 디테일 페이지 화면 디자인 변경
  src/main/resources/templates/medidetail.html
Labels: enhancement

#73 💄 plist 페이지 구현
  src/main/java/com/multi/controller/MainController.java
  src/main/resources/static/assets/ezocss/plistcss.css
  src/main/resources/templates/index.html
  src/main/resources/templates/plist.html
Labels: enhancement

#74 📦 💄 메인페이지에 검색창 및 OCR 버튼 추가
  src/main/resources/static/assets/ezocss/centercss.css
  src/main/resources/static/assets/img/main-logo.png
  src/main/resources/templates/center.html
  src/main/resources/templates/index.html
Labels: enhancement

#77 📦 💄 헤더 로그인 전 후 프로필 바꾸기 및 side bar 로그인/로그아웃 버튼 구현
  src/main/java/com/multi/controller/MainController.java
  src/main/java/com/multi/mybatis/usersmapper.xml
  src/main/resources/static/img/main-logo.png
  src/main/resources/static/img/photo01.jpg
  src/main/resources/templates/center.html
  src/main/resources/templates/index.html
  src/main/resources/templates/profile.html
Labels: enhancement

#79 💄 검색 결과 화면 구성
  src/main/resources/static/assets/ezocss/centercss.css
  src/main/resources/static/img/search_img1.jpg
  src/main/resources/static/img/search_img2.jpg
  src/main/resources/templates/center.html
  src/main/resources/templates/index.html
Labels: enhancement

#81 💄 약 디테일 화면 구성 및 스낵바 구현
  src/main/resources/templates/medidetail.html
Labels: enhancement

#82 📦 처방내역 출력기능 구현
  src/main/java/com/multi/biz/PlistBiz.java
  src/main/java/com/multi/controller/MainController.java
  src/main/java/com/multi/mapper/PlistMapper.java
  src/main/java/com/multi/mybatis/plistmapper.xml
  src/main/java/com/multi/vo/PlistVo.java
  src/main/resources/static/assets/ezocss/plistcss.css
  src/main/resources/templates/index.html
  src/main/resources/templates/plist.html
  src/test/java/com/multi/plist/PlistSelect_EndTests.java
  src/test/java/com/multi/plist/PlistSelect_IngTests.java
Labels: enhancement

#87 💄 📦 복약 캘린더 화면 구현
  src/main/resources/static/fullcalendar/main.css
  src/main/resources/static/fullcalendar/main.js
  src/main/resources/templates/medidetail.html
  src/main/resources/templates/pdetail.html
  src/main/resources/templates/plist.html
Labels: enhancement

#88 📦 내약리스트 기능 구현
  src/main/java/com/multi/biz/MymediBiz.java
  src/main/java/com/multi/controller/MainController.java
  src/main/java/com/multi/mapper/MymediMapper.java
  src/main/java/com/multi/mybatis/mymedimapper.xml
  src/main/resources/templates/mymedi.html
Labels: enhancement

#89 💄 검색 결과 페이지 구현
  src/main/java/com/multi/controller/MainController.java
  src/main/resources/static/assets/ezocss/centercss.css
  src/main/resources/static/assets/ezocss/searchresult.css
  src/main/resources/templates/center.html
  src/main/resources/templates/index.html
  src/main/resources/templates/searchresult.html
Labels: enhancement

#95 💄 footer 고정
  src/main/resources/templates/center.html
  src/main/resources/templates/dashboard.html
  src/main/resources/templates/index.html
  src/main/resources/templates/medidetail.html
  src/main/resources/templates/mymedi.html
  src/main/resources/templates/pdetail.html
  src/main/resources/templates/plist.html
  src/main/resources/templates/profile.html
Labels: enhancement

#96 ✨ 메인페이지(center.html)에 검색결과 출력 기능 구현 완료
  src/main/java/com/multi/controller/AJAXController.java
  src/main/java/com/multi/controller/AJAXTestController.java
  src/main/java/com/multi/restapi/DataAPI.java
  src/main/resources/static/assets/ezocss/centercss.css
  src/main/resources/templates/center.html
  src/main/resources/templates/index.html
  src/main/resources/templates/test/getdataAJAXtest.html
  src/test/java/com/multi/api/DataTest2.java
Labels: enhancement

#94 💄 OCR 이미지 업로드 창 구현
  src/main/resources/templates/center.html
Labels: enhancement

#93 💄 프로필 화면 구현
  src/main/java/com/multi/controller/MainController.java
  src/main/resources/templates/profile.html
Labels: enhancement

#98 📦 signin, signup 페이지 헤더 수정
  src/main/java/com/multi/controller/MainController.java
  src/main/resources/templates/signin.html
  src/main/resources/templates/signup.html
Labels: enhancement

#99 ✨🚧약 디테일 페이지로 이동 기능 구현 중 item을 controller로 보내기 완료
  src/main/java/com/multi/controller/MainController.java
  src/main/resources/static/assets/ezocss/centercss.css
  src/main/resources/templates/center.html
Labels: enhancement

#101 Feature/64
  src/main/java/com/multi/biz/PlistBiz.java
  src/main/java/com/multi/biz/PmediBiz.java
  src/main/java/com/multi/controller/MainController.java
  src/main/java/com/multi/mapper/PlistMapper.java
  src/main/java/com/multi/mapper/PmediMapper.java
  src/main/java/com/multi/mybatis/plistmapper.xml
  src/main/java/com/multi/mybatis/pmedimapper.xml
  src/main/java/com/multi/vo/PmediVo.java
  src/main/resources/templates/pdetail.html
  src/main/resources/templates/plist.html
Labels: enhancement

#102 📦 medidetail 정보 출력 기능 구현
  src/main/java/com/multi/controller/MainController.java
  src/main/resources/templates/center.html
  src/main/resources/templates/medidetail.html
Labels: enhancement

#103 🚧 OCR 이미지 업로드 창 기능 구현 중 코드 공유
  src/main/java/com/multi/controller/AJAXController.java
  src/main/java/com/multi/controller/MainController.java
  src/main/java/com/multi/frame/Util.java
  src/main/java/com/multi/vo/MfVo.java
  src/main/resources/application.properties
  src/main/resources/templates/center.html
Labels: enhancement

#104 ✨ ocr box 스캔 기능 구현(사진 업로드) 완료
  src/main/java/com/multi/controller/AJAXController.java
  src/main/java/com/multi/controller/MainController.java
  src/main/java/com/multi/frame/Util.java
  src/main/resources/templates/center.html
Labels: enhancement

#105 📦 mymedi 추가 기능 구현
  src/main/java/com/multi/controller/AJAXController.java
  src/main/java/com/multi/mybatis/mymedimapper.xml
  src/main/java/com/multi/vo/MymediVo.java
  src/main/resources/templates/medidetail.html
  src/main/resources/templates/mymedi.html
  src/test/java/com/multi/mymedi/MymediInsertTests.java
Labels: enhancement

#106 ✨ 총 스캔된 약들의 양 가져오기 구현
  src/main/java/com/multi/biz/DashBiz.java
  src/main/java/com/multi/controller/MainController.java
  src/main/java/com/multi/mapper/DashMapper.java
  src/main/java/com/multi/mybatis/dashmapper.xml
  src/main/resources/templates/dashboard.html
Labels: enhancement

#107 ✨ 분류 검색 기능 추가
  src/main/java/com/multi/controller/AJAXController.java
  src/main/java/com/multi/controller/MainController.java
  src/main/java/com/multi/restapi/DataAPI2.java
  src/main/java/com/multi/restapi/DataAPI3.java
  src/main/resources/templates/center.html
Labels: enhancement

#111 ✨ 메인 페이지 ocr 창 기능 구현 완료
  src/main/java/com/multi/biz/SlistBiz.java
  src/main/java/com/multi/controller/MainController.java
  src/main/java/com/multi/mapper/SlistMapper.java
  src/main/java/com/multi/mybatis/slistmapper.xml
  src/main/java/com/multi/vo/SlistVo.java
  src/test/java/com/multi/slist/SlistInsertboxTests.java
  src/test/java/com/multi/slist/SlistSelectTheOneTests.java
Labels: enhancement

#113 ✨ 이메일 유효성 체크 , 아이디 중복 체크
  src/main/java/com/multi/biz/UsersBiz.java
  src/main/java/com/multi/controller/AJAXController.java
  src/main/java/com/multi/mapper/UsersMapper.java
  src/main/java/com/multi/mybatis/usersmapper.xml
  src/main/resources/templates/signup.html
Labels: enhancement

#114 ✨ profile update
  src/main/java/com/multi/controller/MainController.java
  src/main/java/com/multi/mybatis/usersmapper.xml
  src/main/resources/templates/profile.html
Labels: enhancement

#116 ✨ 처방약 기능 구현
  src/main/resources/templates/pdetail.html
Labels: enhancement
